import { Providers } from "@/components/Providers";
import { Inter } from "next/font/google";
import { AuthGuard } from "@/components/AuthGuard";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard | Admin | Communikit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <Providers>
        <body
          className={`flex flex-col w-full h-full bg-[#0d1117] text-[#e6edf3]`}
        >
          <AuthGuard>{children}</AuthGuard>
        </body>
      </Providers>
    </html>
  );
}
