version: '3.8'

services:
  advo-kit-db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=advokit
      - MYSQL_ROOT_PASSWORD=advokit
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
