name: Deploy to production
on:
  push:
    branches:
      - main
jobs:
  run-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: pnpm/action-setup@v2
        with:
          version: 7.15.0
          run_install: true
      - run: pnpm prisma:generate
      - run: cd apps/api && pnpm prisma:migrate:deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl apps create-deployment d5b4fb74-f430-4fb5-ace4-45df0e73d2f5
